ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' External Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'MU_R = ', MU_R
      WRITE(*,*) 'aEWM1 = ', AEWM1
      WRITE(*,*) 'mdl_Gf = ', MDL_GF
      WRITE(*,*) 'aS = ', AS
      WRITE(*,*) 'mdl_ymb = ', MDL_YMB
      WRITE(*,*) 'mdl_ymt = ', MDL_YMT
      WRITE(*,*) 'mdl_ymtau = ', MDL_YMTAU
      WRITE(*,*) 'mdl_yLL1x1 = ', MDL_YLL1X1
      WRITE(*,*) 'mdl_yLL1x2 = ', MDL_YLL1X2
      WRITE(*,*) 'mdl_yLL1x3 = ', MDL_YLL1X3
      WRITE(*,*) 'mdl_yLL2x1 = ', MDL_YLL2X1
      WRITE(*,*) 'mdl_yLL2x2 = ', MDL_YLL2X2
      WRITE(*,*) 'mdl_yLL2x3 = ', MDL_YLL2X3
      WRITE(*,*) 'mdl_yLL3x1 = ', MDL_YLL3X1
      WRITE(*,*) 'mdl_yLL3x2 = ', MDL_YLL3X2
      WRITE(*,*) 'mdl_yLL3x3 = ', MDL_YLL3X3
      WRITE(*,*) 'mdl_MZ = ', MDL_MZ
      WRITE(*,*) 'mdl_MTA = ', MDL_MTA
      WRITE(*,*) 'mdl_MT = ', MDL_MT
      WRITE(*,*) 'mdl_MB = ', MDL_MB
      WRITE(*,*) 'mdl_MH = ', MDL_MH
      WRITE(*,*) 'mdl_MS3 = ', MDL_MS3
      WRITE(*,*) 'mdl_WZ = ', MDL_WZ
      WRITE(*,*) 'mdl_WW = ', MDL_WW
      WRITE(*,*) 'mdl_WT = ', MDL_WT
      WRITE(*,*) 'mdl_WH = ', MDL_WH
      WRITE(*,*) 'mdl_WS323 = ', MDL_WS323
      WRITE(*,*) 'mdl_WS313 = ', MDL_WS313
      WRITE(*,*) 'mdl_WS343 = ', MDL_WS343
      WRITE(*,*)  ' Internal Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_MZ__exp__2 = ', MDL_MZ__EXP__2
      WRITE(*,*) 'mdl_MZ__exp__4 = ', MDL_MZ__EXP__4
      WRITE(*,*) 'mdl_sqrt__2 = ', MDL_SQRT__2
      WRITE(*,*) 'mdl_MH__exp__2 = ', MDL_MH__EXP__2
      WRITE(*,*) 'mdl_complexi = ', MDL_COMPLEXI
      WRITE(*,*) 'mdl_MB__exp__2 = ', MDL_MB__EXP__2
      WRITE(*,*) 'mdl_MT__exp__2 = ', MDL_MT__EXP__2
      WRITE(*,*) 'mdl_MS3__exp__2 = ', MDL_MS3__EXP__2
      WRITE(*,*) 'mdl_aEW = ', MDL_AEW
      WRITE(*,*) 'mdl_MW = ', MDL_MW
      WRITE(*,*) 'mdl_sqrt__aEW = ', MDL_SQRT__AEW
      WRITE(*,*) 'mdl_ee = ', MDL_EE
      WRITE(*,*) 'mdl_MW__exp__2 = ', MDL_MW__EXP__2
      WRITE(*,*) 'mdl_sw2 = ', MDL_SW2
      WRITE(*,*) 'mdl_cw = ', MDL_CW
      WRITE(*,*) 'mdl_sqrt__sw2 = ', MDL_SQRT__SW2
      WRITE(*,*) 'mdl_sw = ', MDL_SW
      WRITE(*,*) 'mdl_g1 = ', MDL_G1
      WRITE(*,*) 'mdl_gw = ', MDL_GW
      WRITE(*,*) 'mdl_vev = ', MDL_VEV
      WRITE(*,*) 'mdl_vev__exp__2 = ', MDL_VEV__EXP__2
      WRITE(*,*) 'mdl_lam = ', MDL_LAM
      WRITE(*,*) 'mdl_yb = ', MDL_YB
      WRITE(*,*) 'mdl_yt = ', MDL_YT
      WRITE(*,*) 'mdl_ytau = ', MDL_YTAU
      WRITE(*,*) 'mdl_muH = ', MDL_MUH
      WRITE(*,*) 'mdl_ee__exp__2 = ', MDL_EE__EXP__2
      WRITE(*,*) 'mdl_sw__exp__2 = ', MDL_SW__EXP__2
      WRITE(*,*) 'mdl_cw__exp__2 = ', MDL_CW__EXP__2
      WRITE(*,*) 'mdl_yb__exp__2 = ', MDL_YB__EXP__2
      WRITE(*,*) 'mdl_yt__exp__2 = ', MDL_YT__EXP__2
      WRITE(*,*)  ' Internal Params evaluated point by point'
      WRITE(*,*)  ' ----------------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_sqrt__aS = ', MDL_SQRT__AS
      WRITE(*,*) 'mdl_G__exp__2 = ', MDL_G__EXP__2
      WRITE(*,*) 'mdl_G__exp__3 = ', MDL_G__EXP__3
      WRITE(*,*) 'mdl_G__exp__4 = ', MDL_G__EXP__4
