ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=4D0)
      DOUBLE PRECISION NL
      PARAMETER(NL=2D0)

      DOUBLE PRECISION MDL_MB,MDL_MH,MDL_MS1T,MDL_MT,MDL_MTA,MDL_MW
     $ ,MDL_MZ

      COMMON/MASSES/ MDL_MB,MDL_MH,MDL_MS1T,MDL_MT,MDL_MTA,MDL_MW
     $ ,MDL_MZ


      DOUBLE PRECISION MDL_WH,MDL_WS1T,MDL_WT,MDL_WW,MDL_WZ

      COMMON/WIDTHS/ MDL_WH,MDL_WS1T,MDL_WT,MDL_WW,MDL_WZ


      DOUBLE COMPLEX GC_11, GC_12, GC_65, GC_68

      COMMON/COUPLINGS/ GC_11, GC_12, GC_65, GC_68

