C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     (ProjP(2,1)) * C(51,2) * C(52,1)
C     
      SUBROUTINE FFS5C1P1N_3(F2, F1, COUP,S3)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 S3(3)
      COMPLEX*16 TMP2
      TMP2 = (F1(5)*F2(5)+F1(6)*F2(6))
      S3(3)= COUP*(-CI )* TMP2
      END


